import type { ExerciseType, MuscleGroup } from '@/types';

interface PredefinedExercise {
  name: string;
  type: ExerciseType;
  muscleGroup: MuscleGroup;
  muscleGroups: MuscleGroup[];
  illustration: string;
  restSeconds: number;
}

export const PREDEFINED_EXERCISES: PredefinedExercise[] = [
  // Chest
  {
    name: 'Bench Press',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest', 'arms', 'shoulders'],
    illustration: 'bench-press',
    restSeconds: 120,
  },
  {
    name: 'Incline Bench Press',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest', 'arms', 'shoulders'],
    illustration: 'incline-bench-press',
    restSeconds: 120,
  },
  {
    name: 'Dumbbell Fly',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest'],
    illustration: 'dumbbell-fly',
    restSeconds: 90,
  },
  {
    name: 'Push-ups',
    type: 'calisthenics',
    muscleGroup: 'chest',
    muscleGroups: ['chest', 'arms', 'shoulders'],
    illustration: 'push-ups',
    restSeconds: 60,
  },
  {
    name: 'Cable Crossover',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest'],
    illustration: 'cable-crossover',
    restSeconds: 60,
  },
  {
    name: 'Decline Bench Press',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest', 'arms', 'shoulders'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Dumbbell Bench Press',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest', 'arms', 'shoulders'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Incline Dumbbell Press',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest', 'arms', 'shoulders'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Pec Deck',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Chest Dip',
    type: 'calisthenics',
    muscleGroup: 'chest',
    muscleGroups: ['chest', 'arms', 'shoulders'],
    illustration: '',
    restSeconds: 90,
  },

  // Back
  {
    name: 'Deadlift',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'legs', 'core'],
    illustration: 'deadlift',
    restSeconds: 180,
  },
  {
    name: 'Barbell Row',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: 'barbell-row',
    restSeconds: 120,
  },
  {
    name: 'Lat Pulldown',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: 'lat-pulldown',
    restSeconds: 90,
  },
  {
    name: 'Pull-ups',
    type: 'calisthenics',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: 'pull-ups',
    restSeconds: 90,
  },
  {
    name: 'Seated Cable Row',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: 'seated-cable-row',
    restSeconds: 90,
  },
  {
    name: 'T-Bar Row',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Dumbbell Row',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Chin-ups',
    type: 'calisthenics',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Straight Arm Pulldown',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Pendlay Row',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Cable Pullover',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back'],
    illustration: '',
    restSeconds: 60,
  },

  // Legs
  {
    name: 'Squat',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'core'],
    illustration: 'squat',
    restSeconds: 180,
  },
  {
    name: 'Leg Press',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: 'leg-press',
    restSeconds: 120,
  },
  {
    name: 'Romanian Deadlift',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'back'],
    illustration: 'romanian-deadlift',
    restSeconds: 120,
  },
  {
    name: 'Leg Extension',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: 'leg-extension',
    restSeconds: 60,
  },
  {
    name: 'Leg Curl',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: 'leg-curl',
    restSeconds: 60,
  },
  {
    name: 'Calf Raise',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: 'calf-raise',
    restSeconds: 60,
  },
  {
    name: 'Lunges',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'core'],
    illustration: 'lunges',
    restSeconds: 90,
  },
  {
    name: 'Front Squat',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'core'],
    illustration: '',
    restSeconds: 180,
  },
  {
    name: 'Hack Squat',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Sumo Deadlift',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'back', 'core'],
    illustration: '',
    restSeconds: 180,
  },
  {
    name: 'Bulgarian Split Squat',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'core'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Hip Thrust',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Goblet Squat',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'core'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Walking Lunges',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'core'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Seated Calf Raise',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: '',
    restSeconds: 60,
  },

  // Shoulders
  {
    name: 'Overhead Press',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders', 'arms', 'core'],
    illustration: 'overhead-press',
    restSeconds: 120,
  },
  {
    name: 'Lateral Raise',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders'],
    illustration: 'lateral-raise',
    restSeconds: 60,
  },
  {
    name: 'Front Raise',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders'],
    illustration: 'front-raise',
    restSeconds: 60,
  },
  {
    name: 'Face Pull',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders'],
    illustration: 'face-pull',
    restSeconds: 60,
  },
  {
    name: 'Dumbbell Shoulder Press',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders', 'arms', 'core'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Arnold Press',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders', 'arms', 'core'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Cable Lateral Raise',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Reverse Fly',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Upright Row',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders', 'arms'],
    illustration: '',
    restSeconds: 90,
  },

  // Arms
  {
    name: 'Barbell Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: 'barbell-curl',
    restSeconds: 60,
  },
  {
    name: 'Hammer Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: 'hammer-curl',
    restSeconds: 60,
  },
  {
    name: 'Tricep Pushdown',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: 'tricep-pushdown',
    restSeconds: 60,
  },
  {
    name: 'Skull Crusher',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: 'skull-crusher',
    restSeconds: 90,
  },
  {
    name: 'Dips',
    type: 'calisthenics',
    muscleGroup: 'arms',
    muscleGroups: ['arms', 'chest', 'shoulders'],
    illustration: 'dips',
    restSeconds: 90,
  },
  {
    name: 'Preacher Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'EZ Bar Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Concentration Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Cable Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Close Grip Bench Press',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms', 'chest'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Overhead Tricep Extension',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Tricep Kickback',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Diamond Push-ups',
    type: 'calisthenics',
    muscleGroup: 'arms',
    muscleGroups: ['arms', 'chest'],
    illustration: '',
    restSeconds: 60,
  },

  // Core
  {
    name: 'Plank',
    type: 'flexibility',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: 'plank',
    restSeconds: 30,
  },
  {
    name: 'Hanging Leg Raise',
    type: 'calisthenics',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: 'hanging-leg-raise',
    restSeconds: 60,
  },
  {
    name: 'Ab Crunch',
    type: 'calisthenics',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: 'ab-crunch',
    restSeconds: 30,
  },
  {
    name: 'Russian Twist',
    type: 'calisthenics',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: 'russian-twist',
    restSeconds: 30,
  },
  {
    name: 'Cable Crunch',
    type: 'weights',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Woodchoppers',
    type: 'weights',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Dead Bug',
    type: 'calisthenics',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 30,
  },
  {
    name: 'Mountain Climbers',
    type: 'hiit',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 30,
  },
  {
    name: 'Ab Wheel Rollout',
    type: 'calisthenics',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 60,
  },

  // Cardio
  {
    name: 'Running',
    type: 'cardio',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: 'running',
    restSeconds: 0,
  },
  {
    name: 'Cycling',
    type: 'cardio',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: 'cycling',
    restSeconds: 0,
  },
  {
    name: 'Rowing Machine',
    type: 'cardio',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: 'rowing-machine',
    restSeconds: 0,
  },
  {
    name: 'Jump Rope',
    type: 'hiit',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: 'jump-rope',
    restSeconds: 30,
  },
  {
    name: 'Burpees',
    type: 'hiit',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: 'burpees',
    restSeconds: 30,
  },

  // Full Body
  {
    name: 'Clean and Press',
    type: 'weights',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Kettlebell Swing',
    type: 'weights',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: "Farmer's Walk",
    type: 'weights',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Battle Ropes',
    type: 'hiit',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 30,
  },
  {
    name: 'Box Jump',
    type: 'hiit',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 60,
  },

  // Flexibility
  {
    name: 'Stretching',
    type: 'flexibility',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: 'stretching',
    restSeconds: 0,
  },

  // --- Additional exercises (v0.1.1) ---

  // Chest (additional)
  {
    name: 'Cable Fly',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Smith Machine Bench Press',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest', 'arms', 'shoulders'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Machine Chest Press',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest', 'arms', 'shoulders'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Landmine Press',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest', 'shoulders'],
    illustration: '',
    restSeconds: 90,
  },

  // Back (additional)
  {
    name: 'Rack Pull',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'legs', 'core'],
    illustration: '',
    restSeconds: 180,
  },
  {
    name: 'Meadows Row',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Single Arm Cable Row',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Prone Row',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Reverse Grip Lat Pulldown',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Machine Row',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 90,
  },

  // Legs (additional)
  {
    name: 'Seated Leg Curl',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Sissy Squat',
    type: 'calisthenics',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Smith Machine Squat',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'core'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Glute Kickback Machine',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Step-ups',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'core'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Box Squat',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'core'],
    illustration: '',
    restSeconds: 120,
  },

  // Shoulders (additional)
  {
    name: 'Machine Shoulder Press',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders', 'arms'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Landmine Lateral Raise',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Barbell Shrug',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Behind Neck Press',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders', 'arms'],
    illustration: '',
    restSeconds: 120,
  },

  // Arms (additional)
  {
    name: 'Spider Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Machine Preacher Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Wrist Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 30,
  },
  {
    name: 'Reverse Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Rope Pushdown',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },

  // Full Body (additional)
  {
    name: 'Thruster',
    type: 'weights',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Power Clean',
    type: 'weights',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 150,
  },
  {
    name: 'Snatch',
    type: 'weights',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 180,
  },

  // --- Additional exercises (v0.2) ---

  // Chest
  {
    name: 'Svend Press',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Floor Press',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest', 'arms'],
    illustration: '',
    restSeconds: 120,
  },

  // Back
  {
    name: 'Chest-Supported Row',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Single-Arm Dumbbell Row',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Inverted Row',
    type: 'calisthenics',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 60,
  },

  // Legs
  {
    name: 'Leg Press Calf Raise',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Single-Leg Leg Press',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Good Morning',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'back', 'core'],
    illustration: '',
    restSeconds: 120,
  },

  // Shoulders
  {
    name: 'Prone Y-Raise',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Band Pull-Apart',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders'],
    illustration: '',
    restSeconds: 30,
  },
  {
    name: 'Pike Push-ups',
    type: 'calisthenics',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders', 'arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Reverse Pec Deck',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Lu Raise',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders'],
    illustration: '',
    restSeconds: 60,
  },

  // Arms
  {
    name: 'Bayesian Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Incline Dumbbell Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Close-Grip Push-up',
    type: 'calisthenics',
    muscleGroup: 'arms',
    muscleGroups: ['arms', 'chest'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Dumbbell Kickback',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Cable Overhead Extension',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Zottman Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },

  // Core
  {
    name: 'Decline Crunch',
    type: 'calisthenics',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 30,
  },
  {
    name: 'Pallof Press',
    type: 'weights',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Machine Crunch',
    type: 'weights',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Side Plank',
    type: 'flexibility',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 30,
  },
  {
    name: 'Bicycle Crunch',
    type: 'calisthenics',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 30,
  },

  // Full Body / Cardio
  {
    name: 'Stair Climber',
    type: 'cardio',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: '',
    restSeconds: 0,
  },
  {
    name: 'Elliptical',
    type: 'cardio',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 0,
  },
  {
    name: 'Swimming',
    type: 'cardio',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 0,
  },
  {
    name: 'Walking',
    type: 'cardio',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 0,
  },
  {
    name: 'Sled Push',
    type: 'hiit',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Bear Crawl',
    type: 'calisthenics',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Turkish Get-Up',
    type: 'weights',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Yoga',
    type: 'flexibility',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 0,
  },
  {
    name: 'Foam Rolling',
    type: 'flexibility',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 0,
  },

  // Even more variety
  {
    name: 'Deficit Deadlift',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'legs', 'core'],
    illustration: '',
    restSeconds: 180,
  },
  {
    name: 'Pause Squat',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'core'],
    illustration: '',
    restSeconds: 180,
  },
  {
    name: 'Zercher Squat',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'core', 'arms'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Standing Calf Raise Machine',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Glute Bridge',
    type: 'calisthenics',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Dumbbell Shrug',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Cable Face Pull',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Incline Hammer Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Tricep Dip Machine',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Dragon Flag',
    type: 'calisthenics',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Toe Touch',
    type: 'calisthenics',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 30,
  },
  {
    name: 'V-ups',
    type: 'calisthenics',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 30,
  },
  {
    name: 'Reverse Crunch',
    type: 'calisthenics',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 30,
  },
  {
    name: 'Medicine Ball Slam',
    type: 'hiit',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 30,
  },
  {
    name: 'Wall Ball',
    type: 'hiit',
    muscleGroup: 'full_body',
    muscleGroups: ['full_body'],
    illustration: '',
    restSeconds: 30,
  },

  // --- Additional exercises (v0.3) ---

  // Chest
  {
    name: 'Guillotine Press',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest', 'shoulders'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Spoto Press',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest', 'arms', 'shoulders'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Reverse Grip Bench Press',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest', 'arms'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Hex Press',
    type: 'weights',
    muscleGroup: 'chest',
    muscleGroups: ['chest', 'arms'],
    illustration: '',
    restSeconds: 90,
  },

  // Back
  {
    name: 'Jefferson Curl',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'legs'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Snatch Grip Deadlift',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'legs', 'core'],
    illustration: '',
    restSeconds: 180,
  },
  {
    name: 'Single-Leg Romanian Deadlift',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'legs', 'core'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Helms Row',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Kroc Row',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Low Cable Row',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Wide Grip Cable Row',
    type: 'weights',
    muscleGroup: 'back',
    muscleGroups: ['back', 'arms'],
    illustration: '',
    restSeconds: 90,
  },

  // Legs
  {
    name: 'Nordic Curl',
    type: 'calisthenics',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Glute Ham Raise',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'core'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Reverse Hyper',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'back'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Safety Bar Squat',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'core'],
    illustration: '',
    restSeconds: 180,
  },
  {
    name: 'Copenhagen Adduction',
    type: 'calisthenics',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Single-Leg Press',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Spanish Squat',
    type: 'calisthenics',
    muscleGroup: 'legs',
    muscleGroups: ['legs'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Kaz Squat',
    type: 'weights',
    muscleGroup: 'legs',
    muscleGroups: ['legs', 'core'],
    illustration: '',
    restSeconds: 120,
  },

  // Shoulders
  {
    name: 'Z-Press',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders', 'arms', 'core'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Bradford Press',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders', 'arms'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: '3-Way Shoulder Raise',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Seated Dumbbell Press',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders', 'arms', 'core'],
    illustration: '',
    restSeconds: 120,
  },
  {
    name: 'Leaning Lateral Raise',
    type: 'weights',
    muscleGroup: 'shoulders',
    muscleGroups: ['shoulders'],
    illustration: '',
    restSeconds: 60,
  },

  // Arms
  {
    name: 'JM Press',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms', 'chest'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Tate Press',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'French Press',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 90,
  },
  {
    name: 'Cross-Body Hammer Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Pinwheel Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Overhead Cable Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Pin Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Wide Grip Curl',
    type: 'weights',
    muscleGroup: 'arms',
    muscleGroups: ['arms'],
    illustration: '',
    restSeconds: 60,
  },

  // Core
  {
    name: 'Hollow Body Hold',
    type: 'calisthenics',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 30,
  },
  {
    name: 'Windmill',
    type: 'weights',
    muscleGroup: 'core',
    muscleGroups: ['core', 'shoulders'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Suitcase Carry',
    type: 'weights',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 60,
  },
  {
    name: 'Hanging Knee Raise',
    type: 'calisthenics',
    muscleGroup: 'core',
    muscleGroups: ['core'],
    illustration: '',
    restSeconds: 45,
  },
];
